name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: anefdev
      IMAGE_NAME: flowtherock
      IMAGE_TAG: latest
    
    steps:
    
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './flowtherock-app/flowtherock-app/src/main/resources/application.properties'
        property: |
          'spotify-client-id'
          'spotify-client-secret'
        value: |
          '${{ secrets.SPOTIFY_CLIENT_ID }}'
          '${{ secrets.SPOTIFY_CLIENT_SECRET }}'

    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image
      run:
        docker build ./flowtherock-app/ --file ./flowtherock-app/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG --no-cache
        
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
